server:
  port: 80    #80端口，访问的时候只需要输入ip就好，不需要输入端口号
  
eureka:
  client:
    register-with-eureka: false
    
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/